export const SignupOptions = [
  {
    label: "E-mail",
    backgroundColor: "#0e0e0e",
    iconSrc: "/logo.png",
    altText: "combostart logo",
    width: 32,
    height: 26,
    onClick: () => setShowSignupForm(true),
  },
  {
    label: "Google",
    backgroundColor: "white",
    color: "#1a1a1a",
    iconSrc: "/googleIcon.svg",
    altText: "Google logo",
    width: 26,
    height: 26,
  },
  {
    label: "Steam",
    backgroundColor: "rgb(43, 108, 154)",
    iconSrc: "/steamIcon.svg",
    altText: "Steam logo",
    width: 26,
    height: 26,
  },
  {
    label: "Discord",
    backgroundColor: "#7289DA",
    iconSrc: "/discordIcon.svg",
    altText: "Discord logo",
    width: 26,
    height: 26,
  },
  {
    label: "Xbox Live",
    backgroundColor: "green",
    iconSrc: "/xboxIcon.svg",
    altText: "Xbox logo",
    width: 26,
    height: 26,
  },
  {
    label: "Playstation Network",
    backgroundColor: "#003087",
    iconSrc: "/playstationIcon.svg",
    altText: "Playstation logo",
    width: 26,
    height: 26,
  },
];
