export const comboCardData = [
  {
    id: 1,
    videoUrl: "Phdd6XJovgg",
    super: true,
    punishCounter: true,
    driveRushBars: 4,
    cardTitle: "Ryu advanced 5600 damage corner combo",
    comboDamage: 5600,
    comboHits: 16,
    comboType: "CORNER",
    charName: "Ryu",
    patchVer: "1.0.0",
    notationType: "XBOX",
    author: "SFO Ghost",
    date: "December 20, 2022",
    inputs: [
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
    ],
    tags: [
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
    ],
  },
  {
    id: 2,
    videoUrl: "Phdd6XJovgg",
    super: false,
    punishCounter: false,
    driveRushBars: 2,
    cardTitle: "Ken beginner 2400 damage mid-screen combo",
    comboDamage: 2400,
    comboHits: 10,
    comboType: "MID-SCREEN",
    charName: "Ken",
    patchVer: "1.2.0",
    notationType: "PC",
    author: "SF Champion",
    date: "January 10, 2023",
    inputs: [
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
    ],
    tags: [
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
    ],
  },
  {
    id: 3,
    super: false,
    punishCounter: true,
    driveRushBars: 3,
    cardTitle: "Chun-li intermediate 3800 damage corner combo",
    comboDamage: 3800,
    comboHits: 14,
    comboType: "CORNER",
    charName: "chunli",
    patchVer: "1.1.5",
    notationType: "XBOX",
    author: "Combo Master",
    date: "February 5, 2023",
    inputs: [
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
    ],
    tags: [
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
    ],
  },
  {
    id: 4,
    videoUrl: "Phdd6XJovgg",
    super: true,
    punishCounter: false,
    driveRushBars: 5,
    cardTitle: "Guile expert 7200 damage mid-screen combo",
    comboDamage: 7200,
    comboHits: 22,
    comboType: "MID-SCREEN",
    charName: "Guile",
    patchVer: "1.3.2",
    notationType: "PS4",
    author: "Pro Fighter",
    date: "March 15, 2023",
    inputs: [
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
    ],
    tags: [
      {
        text: "mid-screen",
        src: "/",
        desc: "Combo only performed at the middle of the screens",
      },
      {
        text: "BnB",
        src: "/",
        desc: "Stands for Bread and Butter, a relative basic combo that fits well in most cases",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
    ],
  },
  {
    id: 5,
    videoUrl: "Phdd6XJovgg",
    super: true,
    punishCounter: true,
    driveRushBars: 4,
    cardTitle: "Juri advanced 5600 damage corner combo",
    comboDamage: 5600,
    comboHits: 16,
    comboType: "CORNER",
    charName: "Juri",
    patchVer: "1.0.0",
    notationType: "XBOX",
    author: "Combo King",
    date: "April 1, 2023",
    inputs: [
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
    ],
    tags: [
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
    ],
  },
  {
    id: 6,
    videoUrl: "Phdd6XJovgg",
    super: false,
    punishCounter: false,
    driveRushBars: 2,
    cardTitle: "Ryu beginner 2000 damage mid-screen combo",
    comboDamage: 2000,
    comboHits: 8,
    comboType: "MID-SCREEN",
    charName: "Ryu",
    patchVer: "1.2.0",
    notationType: "PS4",
    author: "SF Rookie",
    date: "May 2, 2023",
    inputs: [
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
    ],
    tags: [
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
    ],
  },
  {
    id: 7,
    super: true,
    punishCounter: false,
    driveRushBars: 4,
    cardTitle: "Cammy advanced 5000 damage corner combo",
    comboDamage: 5000,
    comboHits: 18,
    comboType: "CORNER",
    charName: "Cammy",
    patchVer: "1.0.0",
    notationType: "XBOX",
    author: "SF Prodigy",
    date: "June 10, 2023",
    inputs: [
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
    ],
    tags: [
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
    ],
  },
  {
    id: 8,
    videoUrl: "Phdd6XJovgg",
    super: true,
    punishCounter: true,
    driveRushBars: 4,
    cardTitle: "Luke advanced 5800 damage mid-screen combo",
    comboDamage: 5800,
    comboHits: 14,
    comboType: "MID-SCREEN",
    charName: "Luke",
    patchVer: "1.2.1",
    notationType: "PS4",
    author: "Tiger King",
    date: "September 10, 2023",
    inputs: [
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
    ],
    tags: [
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
    ],
  },
  {
    id: 9,
    super: false,
    punishCounter: true,
    driveRushBars: 3,
    cardTitle: "Kimberly intermediate 4000 damage mid-screen combo",
    comboDamage: 4000,
    comboHits: 12,
    comboType: "MID-SCREEN",
    charName: "Kimberly",
    patchVer: "1.1.5",
    notationType: "PS4",
    author: "Combo Guru",
    date: "July 5, 2023",
    inputs: [
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
    ],
    tags: [
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
    ],
  },
  {
    id: 10,
    videoUrl: "Phdd6XJovgg",
    super: true,
    punishCounter: false,
    driveRushBars: 5,
    cardTitle: "Jamie expert 6500 damage corner combo",
    comboDamage: 6500,
    comboHits: 20,
    comboType: "CORNER",
    charName: "Jamie",
    patchVer: "1.3.2",
    notationType: "XBOX",
    author: "Master Fighter",
    date: "August 20, 2023",
    inputs: [
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
    ],
    tags: [
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
      {
        text: "corner",
        src: "/",
        desc: "Combo only performed at one of the corners of the arena",
      },
    ],
  },
];
