export const comboCardData = [
  {
    id: 1,
    videoUrl: "Phdd6XJovgg",
    super: true,
    punishCounter: true,
    driveRushBars: 4,
    cardTitle: "Ryu advanced 5600 damage corner combo",
    comboDamage: 5600,
    comboHits: 16,
    comboType: "CORNER",
    charName: "Ryu",
    patchVer: "1.0.0",
    notationType: "XBOX",
    author: "SFO Ghost",
    date: "December 20, 2022",
    inputs: [
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
    ],
  },
  {
    id: 2,
    videoUrl: "Phdd6XJovgg",
    super: true,
    punishCounter: true,
    driveRushBars: 4,
    cardTitle: "Ryu advanced 5600 damage corner combo",
    comboDamage: 5600,
    comboHits: 16,
    comboType: "CORNER",
    charName: "Ryu",
    patchVer: "1.0.0",
    notationType: "XBOX",
    author: "SFO Ghost",
    date: "December 20, 2022",
    inputs: [
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
    ],
  },
  {
    id: 3,
    videoUrl: "Phdd6XJovgg",
    super: true,
    punishCounter: true,
    driveRushBars: 4,
    cardTitle: "Ryu advanced 5600 damage corner combo",
    comboDamage: 5600,
    comboHits: 16,
    comboType: "CORNER",
    charName: "Ryu",
    patchVer: "1.0.0",
    notationType: "XBOX",
    author: "SFO Ghost",
    date: "December 20, 2022",
    inputs: [
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
    ],
  },
  {
    id: 4,
    videoUrl: "Phdd6XJovgg",
    super: true,
    punishCounter: true,
    driveRushBars: 4,
    cardTitle: "Ryu advanced 5600 damage corner combo",
    comboDamage: 5600,
    comboHits: 16,
    comboType: "CORNER",
    charName: "Ryu",
    patchVer: "1.0.0",
    notationType: "XBOX",
    author: "SFO Ghost",
    date: "December 20, 2022",
    inputs: [
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
    ],
  },
  {
    id: 5,
    videoUrl: "Phdd6XJovgg",
    super: true,
    punishCounter: true,
    driveRushBars: 4,
    cardTitle: "Ryu advanced 5600 damage corner combo",
    comboDamage: 5600,
    comboHits: 16,
    comboType: "CORNER",
    charName: "Ryu",
    patchVer: "1.0.0",
    notationType: "XBOX",
    author: "SFO Ghost",
    date: "December 20, 2022",
    inputs: [
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
    ],
  },
  {
    id: 6,
    videoUrl: "Phdd6XJovgg",
    super: true,
    punishCounter: true,
    driveRushBars: 4,
    cardTitle: "Ryu advanced 5600 damage corner combo",
    comboDamage: 5600,
    comboHits: 16,
    comboType: "CORNER",
    charName: "Ryu",
    patchVer: "1.0.0",
    notationType: "XBOX",
    author: "SFO Ghost",
    date: "December 20, 2022",
    inputs: [
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
    ],
  },
  {
    id: 7,
    videoUrl: "Phdd6XJovgg",
    super: true,
    punishCounter: true,
    driveRushBars: 4,
    cardTitle: "Ryu advanced 5600 damage corner combo",
    comboDamage: 5600,
    comboHits: 16,
    comboType: "CORNER",
    charName: "Ryu",
    patchVer: "1.0.0",
    notationType: "XBOX",
    author: "SFO Ghost",
    date: "December 20, 2022",
    inputs: [
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
    ],
  },
  {
    id: 8,
    videoUrl: "Phdd6XJovgg",
    super: true,
    punishCounter: true,
    driveRushBars: 4,
    cardTitle: "Ryu advanced 5600 damage corner combo",
    comboDamage: 5600,
    comboHits: 16,
    comboType: "CORNER",
    charName: "Ryu",
    patchVer: "1.0.0",
    notationType: "XBOX",
    author: "SFO Ghost",
    date: "December 20, 2022",
    inputs: [
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
    ],
  },
  {
    id: 9,
    videoUrl: "Phdd6XJovgg",
    super: true,
    punishCounter: true,
    driveRushBars: 4,
    cardTitle: "Ryu advanced 5600 damage corner combo",
    comboDamage: 5600,
    comboHits: 16,
    comboType: "CORNER",
    charName: "Ryu",
    patchVer: "1.0.0",
    notationType: "XBOX",
    author: "SFO Ghost",
    date: "December 20, 2022",
    inputs: [
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
    ],
  },
  {
    id: 10,
    videoUrl: "Phdd6XJovgg",
    super: true,
    punishCounter: true,
    driveRushBars: 4,
    cardTitle: "Ryu advanced 5600 damage corner combo",
    comboDamage: 5600,
    comboHits: 16,
    comboType: "CORNER",
    charName: "Ryu",
    patchVer: "1.0.0",
    notationType: "XBOX",
    author: "SFO Ghost",
    date: "December 20, 2022",
    inputs: [
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickH.svg",
        altText: "Street Fighter heavy kick icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/kickA.svg",
        altText: "Street Fighter medium punch icon input",
        figCaption: "Punch",
      },
      {
        imageSrc: "/inputs/punchL.svg",
        altText: "Street Fighter light punch icon input",
        figCaption: "Punch",
      },
    ],
  },
];
