export const guideCardData = [
  {
    id: 1,
    bgImg: "/sf6coverArt.webp",
    name: "STREET FIGHTER 6",
    src: "/ComboPage",
    attr: "Featured",
  },
  {
    id: 2,
    bgImg: "/tekken7coverArt.jpg",
    name: "TEKKEN 7",
    src: "/ComboPage",
    attr: "Featured",
  },
  {
    id: 3,
    bgImg: "/mk11UltimatecoverArt.webp",
    name: "MORTAL KOMBAT 11",
    src: "/ComboPage",
    attr: "Featured",
  },

  {
    id: 4,
    bgImg: "/guiltygearstrivecoverArt.webp",
    name: "GUILTY GEAR STRIVE",
    src: "/ComboPage",
    attr: "ongoing",
  },
  {
    id: 5,
    bgImg: "/skullgirlscoverArt.jpg",
    name: "SKULLGIRLS",
    src: "/ComboPage",
    attr: "ongoing",
  },
  {
    id: 6,
    bgImg: "/dragonballfighterzcoverArt.webp",
    name: "DRAGON BALL FIGHTERZ",
    src: "/ComboPage",
    attr: "ongoing",
  },
  {
    id: 7,
    bgImg: "/kof15coverArt.jpg",
    name: "THE KING OF FIGHTERS XV",
    src: "/ComboPage",
    attr: "ongoing",
  },
  {
    id: 8,
    bgImg: "/streetfightervcoverArt.webp",
    name: "STREET FIGHTER V",
    src: "/ComboPage",
    attr: "ongoing",
  },
  {
    id: 9,
    bgImg: "/killerinstinct2013coverArt.jpeg",
    name: "KILLER INSTINCT(2013)",
    src: "/ComboPage",
    attr: "ongoing",
  },
  {
    id: 10,
    bgImg: "/granbluefantasycoverArt.jpg",
    name: "GRANBLUE FANTASY VERSUS",
    src: "/ComboPage",
    attr: "ongoing",
  },
  {
    id: 11,
    bgImg: "/brawlhallacoverArt.jpg",
    name: "BRAWLHALLA",
    src: "/ComboPage",
    attr: "ongoing",
  },
  {
    id: 12,
    bgImg: "/meltybloodcoverArt.jpg",
    name: "MELTY BLOOD: TYPE LUMINA",
    src: "/ComboPage",
    attr: "ongoing",
  },
  {
    id: 13,
    bgImg: "/umvsc3coverArt.jpg",
    name: "ULTIMATE MARVEL VS CAPCOM 3",
    src: "/ComboPage",
    attr: "ongoing",
  },
  {
    id: 14,
    bgImg: "/mkxcoverArt.jpg",
    name: "MORTAL KOMBAT X",
    src: "/ComboPage",
    attr: "ongoing",
  },
  {
    id: 15,
    bgImg: "/smashbrosultimatecoverArt.webp",
    name: "SUPER SMASH BROS. ULTIMATE",
    src: "/ComboPage",
    attr: "ongoing",
  },
  {
    id: 16,
    bgImg: "/mkOne2023m.jpg",
    name: "MORTAL KOMBAT 1(2023)",
    src: "/ComboPage",
    attr: "Upcoming",
  },
  {
    id: 17,
    bgImg: "/tekken8.webp",
    name: "TEKKEN 8",
    src: "/ComboPage",
    attr: "Upcoming",
  },
  {
    id: 18,
    bgImg: "/granblueFantasyRising.jpg",
    name: "Granblue Fantasy Rising",
    src: "/ComboPage",
    attr: "Upcoming",
  },
];
