export const inputData = [
  {
    id: 1,
    imageSrc: "/inputs/kickA.svg",
    altText: "Street Fighter medium punch icon input",
    width: 54,
    height: 54,
    figCaption: "B.AK",
  },
  {
    id: 2,
    imageSrc: "/inputs/punchM.svg",
    altText: "Street Fighter medium punch icon input",
    width: 54,
    height: 54,
    figCaption: "S.MP",
  },
  {
    id: 3,
    imageSrc: "/inputs/kickH.svg",
    altText: "Street Fighter medium punch icon input",
    width: 54,
    height: 54,
    figCaption: "S.MP",
  },
  {
    id: 4,
    imageSrc: "/inputs/arrow.svg",
    altText: "Street Fighter medium punch icon input",
    width: 34,
    height: 34,
    figCaption: "F",
  },
  {
    id: 5,
    imageSrc: "/inputs/punchH.svg",
    altText: "Street Fighter medium punch icon input",
    width: 54,
    height: 54,
    figCaption: "S.MP",
  },
  {
    id: 6,
    imageSrc: "/inputs/arrow.svg",
    altText: "Street Fighter medium punch icon input",
    width: 34,
    height: 34,
    figCaption: "F",
  },
  {
    id: 7,
    imageSrc: "/inputs/punchA.svg",
    altText: "Street Fighter medium punch icon input",
    width: 54,
    height: 54,
    figCaption: "F.AP",
  },
  {
    id: 8,
    imageSrc: "/inputs/punchM.svg",
    altText: "Street Fighter medium punch icon input",
    width: 54,
    height: 54,
    figCaption: "QCF.ML",
  },
  {
    id: 9,
    imageSrc: "/inputs/kickL.svg",
    altText: "Street Fighter medium punch icon input",
    width: 54,
    height: 54,
    figCaption: "B.LK",
  },
  {
    id: 10,
    imageSrc: "/inputs/punchH.svg",
    altText: "Street Fighter medium punch icon input",
    width: 54,
    height: 54,
    figCaption: "S.HP",
  },
];
