export const inputData = [
  {
    id: 1,
    imageSrc: "/inputs/kickA.svg",
    altText: "Street Fighter medium punch icon input",
    width: 44,
    height: 44,
    figCaption: "PC",
  },
  {
    id: 2,
    imageSrc: "/inputs/punchM.svg",
    altText: "Street Fighter medium punch icon input",
    width: 44,
    height: 44,
    figCaption: "DC",
  },
  {
    id: 3,
    imageSrc: "/inputs/kickH.svg",
    altText: "Street Fighter medium punch icon input",
    width: 44,
    height: 44,
    figCaption: "S.HK",
  },
  {
    id: 4,
    imageSrc: "/inputs/arrow.svg",
    altText: "Street Fighter medium punch icon input",
    width: 34,
    height: 34,
    figCaption: "C.HP",
  },
  {
    id: 5,
    imageSrc: "/inputs/punchH.svg",
    altText: "Street Fighter medium punch icon input",
    width: 44,
    height: 44,
    figCaption: "DR",
  },
  {
    id: 6,
    imageSrc: "/inputs/arrow.svg",
    altText: "Street Fighter medium punch icon input",
    width: 34,
    height: 34,
    figCaption: "S.HK",
  },
  {
    id: 7,
    imageSrc: "/inputs/punchA.svg",
    altText: "Street Fighter medium punch icon input",
    width: 44,
    height: 44,
    figCaption: "C.HP",
  },
  {
    id: 8,
    imageSrc: "/inputs/punchM.svg",
    altText: "Street Fighter medium punch icon input",
    width: 44,
    height: 44,
    figCaption: "QCB.P",
  },
  {
    id: 9,
    imageSrc: "/inputs/kickL.svg",
    altText: "Street Fighter medium punch icon input",
    width: 44,
    height: 44,
    figCaption: "DR",
  },
  {
    id: 10,
    imageSrc: "/inputs/punchH.svg",
    altText: "Street Fighter medium punch icon input",
    width: 44,
    height: 44,
    figCaption: "C.HP",
  },
  {
    id: 11,
    imageSrc: "/inputs/punchH.svg",
    altText: "Street Fighter medium punch icon input",
    width: 44,
    height: 44,
    figCaption: "QCB.MP",
  },
  {
    id: 12,
    imageSrc: "/inputs/punchH.svg",
    altText: "Street Fighter medium punch icon input",
    width: 44,
    height: 44,
    figCaption: "DP.HP",
  },
  {
    id: 13,
    imageSrc: "/inputs/punchH.svg",
    altText: "Street Fighter medium punch icon input",
    width: 44,
    height: 44,
    figCaption: "QCF.QCF.K",
  },
];
